name: Zip Files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Get the latest tag
      id: get_tag
      run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Zip files
      run: zip wp-web-vitals-${{ env.tag }}.zip wp-web-vitals.php wp-web-vitals.js LICENCE

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp-web-vitals-${{ env.tag }}
        path: wp-web-vitals-${{ env.tag }}.zip