name: Zip Files

on:
  push:
    tags:
      - '*.*.*'

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Zip files
      run: zip wp-web-vitals-${{ github.ref_name }}.zip wp-web-vitals.php wp-web-vitals.js LICENCE

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp-web-vitals-${{ github.ref_name }}
        path: wp-web-vitals-${{ github.ref_name }}.zip